meta:  
  areas:
  - id: 0
    area-name: 未設定
    area-short-name: 未
    area-eng-name: unknown
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 1
    area-name: 神戸
    area-short-name: 神
    area-eng-name: kobe
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 2
    area-name: 阪神
    area-short-name: 阪
    area-eng-name: hanshin
    text-color: "000000"
    bg-red: 200
    bg-green: 200
    bg-blue: 51
    bg-alpha: 0.9
  - id: 3
    area-name: 丹波
    area-short-name: 丹
    area-eng-name: tanba
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 4
    area-name: 但馬
    area-short-name: 但
    area-eng-name: tajima
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 5
    area-name: 西播
    area-short-name: 西
    area-eng-name: seiban
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 6
    area-name: 東播
    area-short-name: 東
    area-eng-name: touban
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
  - id: 7
    area-name: 淡路
    area-short-name: 淡
    area-eng-name: awaji
    text-color: "000000"
    bg-red: 0
    bg-green: 0
    bg-blue: 0
    bg-alpha: 0
