name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - "hyogo-master"
      - "hyogo-develop"
    tags:
      - "*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/hyogo-master'
        with:
          context: .
          push: true
          tags: pinfort/mastodon:latest
          cache-from: type=registry,ref=pinfort/mastodon:latest
          cache-to: type=inline
      - uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/hyogo-develop'
        with:
          context: .
          push: true
          tags: pinfort/mastodon:development
          cache-from: type=registry,ref=pinfort/mastodon:development
          cache-to: type=inline
