name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - "hyogo-master"
      - "hyogo-develop"
    tags:
      - "*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        if: github.ref == 'refs/heads/hyogo-master'
        id: meta-master
        with:
          images: pinfort/mastodon
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=hyogo-master
            type=semver,pattern={{ raw }}
      - uses: docker/metadata-action@v3
        if: github.ref == 'refs/heads/hyogo-develop'
        id: meta-develop
        with:
          images: pinfort/mastodon
          flavor: |
            latest=false
          tags: |
            type=edge,branch=hyogo-develop
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=pinfort/mastodon:latest
          cache-to: type=inline
